"""table enum module."""

from enum import Enum
from abstractions import EnumLayer
from constants import DBTable, Model


class DBTableENUM(EnumLayer):
    ACTIVITY = DBTable.ACTIVITY
    ACTIVITY_TYPE_LK = DBTable.ACTIVITY_TYPE_LK
    AI_SCREENING_CONFIG = DBTable.AI_SCREENING_CONFIG
    AI_SCREENING_CRITERIA = DBTable.AI_SCREENING_CRITERIA
    AI_SCREENING_EVALUATION = DBTable.AI_SCREENING_EVALUATION
    AI_SCREENING_RUN = DBTable.AI_SCREENING_RUN
    AI_SCREENING_STATUS_LK = DBTable.AI_SCREENING_STATUS_LK
    APPLICATION = DBTable.APPLICATION
    APPLICATION_PIPELINE = DBTable.APPLICATION_PIPELINE
    AUTH_TYPE_LK = DBTable.AUTH_TYPE_LK
    AUTOMATION_RULE = DBTable.AUTOMATION_RULE
    BACKGROUND_CHECK = DBTable.BACKGROUND_CHECK
    BG_CHECK_STATUS_LK = DBTable.BG_CHECK_STATUS_LK
    BOARD_POSTING = DBTable.BOARD_POSTING
    BOARD_STATUS_LK = DBTable.BOARD_STATUS_LK
    CAMPAIGN = DBTable.CAMPAIGN
    CAMPAIGN_STEP = DBTable.CAMPAIGN_STEP
    CANDIDATE = DBTable.CANDIDATE
    CANDIDATE_LINK = DBTable.CANDIDATE_LINK
    CANDIDATE_LOCATION = DBTable.CANDIDATE_LOCATION
    CANDIDATE_SKILL = DBTable.CANDIDATE_SKILL
    CANDIDATE_TAG = DBTable.CANDIDATE_TAG
    CANDIDATE_UPLOAD = DBTable.CANDIDATE_UPLOAD
    CAREER_CONFIG = DBTable.CAREER_CONFIG
    COMPANY = DBTable.COMPANY
    COUNTRY_LK = DBTable.COUNTRY_LK
    CURRENCY_LK = DBTable.CURRENCY_LK
    DEDUP_GROUP = DBTable.DEDUP_GROUP
    DEDUP_GROUP_CANDIDATE = DBTable.DEDUP_GROUP_CANDIDATE
    E_SIGNATURE = DBTable.E_SIGNATURE
    EMPLOYMENT_CONFIG = DBTable.EMPLOYMENT_CONFIG
    EMPLOYMENT_TYPE_LK = DBTable.EMPLOYMENT_TYPE_LK
    ENROLLMENT = DBTable.ENROLLMENT
    ENROLLMENT_STATUS_LK = DBTable.ENROLLMENT_STATUS_LK
    INTEGRATION = DBTable.INTEGRATION
    INTEGRATION_CATEGORY_LK = DBTable.INTEGRATION_CATEGORY_LK
    INTERVIEW = DBTable.INTERVIEW
    INTERVIEW_INTERVIEWER = DBTable.INTERVIEW_INTERVIEWER
    INTERVIEW_KIT = DBTable.INTERVIEW_KIT
    INTERVIEW_KIT_QUESTION = DBTable.INTERVIEW_KIT_QUESTION
    INTERVIEW_STATUS_LK = DBTable.INTERVIEW_STATUS_LK
    INTERVIEW_TYPE_LK = DBTable.INTERVIEW_TYPE_LK
    JOB = DBTable.JOB
    JOB_DOMAIN_LK = DBTable.JOB_DOMAIN_LK
    JOB_INTERVIEW_PLAN = DBTable.JOB_INTERVIEW_PLAN
    JOB_INTERVIEW_PLAN_INTERVIEWER = DBTable.JOB_INTERVIEW_PLAN_INTERVIEWER
    JOB_LOCATION = DBTable.JOB_LOCATION
    JOB_ROLE = DBTable.JOB_ROLE
    JOB_ROLE_LEVEL_LK = DBTable.JOB_ROLE_LEVEL_LK
    JOB_SKILL = DBTable.JOB_SKILL
    JOB_STAGE = DBTable.JOB_STAGE
    JOB_STATUS_LK = DBTable.JOB_STATUS_LK
    LOCATION_LK = DBTable.LOCATION_LK
    MFA_TYPE_LK = DBTable.MFA_TYPE_LK
    NOTIFICATION = DBTable.NOTIFICATION
    NOTIFICATION_KIND_LK = DBTable.NOTIFICATION_KIND_LK
    OFFER = DBTable.OFFER
    OFFER_STATUS_LK = DBTable.OFFER_STATUS_LK
    OTP_TYPE_LK = DBTable.OTP_TYPE_LK
    PORTAL_APPLICATION = DBTable.PORTAL_APPLICATION
    RATING_LK = DBTable.RATING_LK
    RECOMMENDATION_LK = DBTable.RECOMMENDATION_LK
    REPORT_DIMENSION_LK = DBTable.REPORT_DIMENSION_LK
    REPORT_METRIC_LK = DBTable.REPORT_METRIC_LK
    REQ_STATUS_LK = DBTable.REQ_STATUS_LK
    REQUISITION = DBTable.REQUISITION
    REQUISITION_APPROVAL = DBTable.REQUISITION_APPROVAL
    RULE_ACTION_LK = DBTable.RULE_ACTION_LK
    RULE_RUN = DBTable.RULE_RUN
    RULE_TRIGGER_LK = DBTable.RULE_TRIGGER_LK
    SAVED_REPORT = DBTable.SAVED_REPORT
    SCHEDULING_LINK = DBTable.SCHEDULING_LINK
    SCHEDULING_LINK_INTERVIEWER = DBTable.SCHEDULING_LINK_INTERVIEWER
    SCHEDULING_LINK_STATUS_LK = DBTable.SCHEDULING_LINK_STATUS_LK
    SCORECARD = DBTable.SCORECARD
    SCORECARD_ATTRIBUTE = DBTable.SCORECARD_ATTRIBUTE
    SIGN_STATUS_LK = DBTable.SIGN_STATUS_LK
    SKILL_LK = DBTable.SKILL_LK
    SOURCED_PROFILE = DBTable.SOURCED_PROFILE
    SOURCED_PROFILE_SKILL = DBTable.SOURCED_PROFILE_SKILL
    STAGE_CONFIG = DBTable.STAGE_CONFIG
    TEMPLATE = DBTable.TEMPLATE
    TEMPLATE_TYPE_LK = DBTable.TEMPLATE_TYPE_LK
    TENANT = DBTable.TENANT
    TENANT_PROFILE = DBTable.TENANT_PROFILE
    UPLOAD_TYPE_LK = DBTable.UPLOAD_TYPE_LK
    USER = DBTable.USER
    USER_OTP = DBTable.USER_OTP
    USER_RECOVERY_CODE = DBTable.USER_RECOVERY_CODE
    USER_TYPE_LK = DBTable.USER_TYPE_LK

    @property
    def name(self) -> str:
        """Returns the layer name."""
        return "DBTableENUM"

