"""log enum module."""

from enum import Enum
from abstractions import EnumLayer
from constants import Log


class LogENUM(EnumLayer):
    APP_STARTED = Log.APP_STARTED
    APP_SHUTDOWN = Log.APP_SHUTDOWN
    CONTROLLER_STARTED = Log.CONTROLLER_STARTED
    CONTROLLER_COMPLETED = Log.CONTROLLER_COMPLETED
    CONTROLLER_FAILED = Log.CONTROLLER_FAILED
    REQUEST_STARTED = Log.REQUEST_STARTED
    REQUEST_COMPLETED = Log.REQUEST_COMPLETED
    REQUEST_FAILED = Log.REQUEST_FAILED
    DB_QUERY_SLOW = Log.DB_QUERY_SLOW
    REPOSITORY_STARTED = Log.REPOSITORY_STARTED
    REPOSITORY_COMPLETED = Log.REPOSITORY_COMPLETED
    REPOSITORY_FAILED = Log.REPOSITORY_FAILED
    REPOSITORY_OPERATION = Log.REPOSITORY_OPERATION
    SERVICE_STARTED = Log.SERVICE_STARTED
    SERVICE_COMPLETED = Log.SERVICE_COMPLETED
    SERVICE_FAILED = Log.SERVICE_FAILED
    UTILITY_STARTED = Log.UTILITY_STARTED
    UTILITY_COMPLETED = Log.UTILITY_COMPLETED
    UTILITY_FAILED = Log.UTILITY_FAILED

    @property
    def name(self) -> str:
        """Returns the layer name."""
        return "LogENUM"

